- service: Luxury Rooms
  description: Clean, updated rooms.
  icon: flaticon-double-bed

- service: Fast & Free Wifi
  description: All of our rooms are equipped with fast, free wifi for all your browsing needs.
  icon: flaticon-wifi

- service: Parking
  description: Parking is spacious, free, and easy. We also have ample space for truck parking.
  icon: flaticon-taxi

- service: Accepts Credit Card and Cash
  description: We accept any credit card as well as cash for payment.
  icon: flaticon-credit-card

- service: Breakfast
  description: We offer a free continental breakfast every morning. **Temporarily closed due to COVID-19.**
  icon: flaticon-snack
